### PR TITLE
Moved analytics to theme. Also implemented it in head.html! :)

### PR DESCRIPTION
**Pull request by sammyjava**
Turns out I didn't HAVE analytics.html included in head.html in the non-theme LIS site (oops). I'm sure a MILLION USERS have been viewing our website!

In any case, I've moved analytics.html over to the theme AND implemented it in the theme's head.html. It works.

### CODE REVIEW

**Comment by sammyjava** [comment]
@alancleary note I did not include a default `google_analytics` value in the theme's _config.yml, as I think that will throw an error on a bogus ID, but I don't want to use the LIS site ID since then anyone that leaves it out of their site's _config.yml will end up adding to the LIS stats. Not sure how to best deal with this.

**Review by alancleary — CHANGES_REQUESTED** [review]
Thanks for porting this over @sammyjava. No need to provide a default value for the Google Analytics variable in the `_config.yml` file. You just need add a liquid [`if` block](https://shopify.github.io/liquid/tags/control-flow/) around the code in `_includes/analytics.html` so it won't add the code unless a value is provided for the variable in the config. Please rename the variable `google_analytics_id` so it's more verbose and document its usage in the `_config.yml` section of the README.

**Review by alancleary — CHANGES_REQUESTED** [review]
Looks good. However, I changed the `_config.yml` section of the README in main before submitting my last review so that  your changes wouldn't perpetuate the formatting errors, but it looks like you squashed those changes! Mind changing it back?

**Comment by sammyjava** [comment]
OH! I thought I preserved your recent change in my merge, but I did the opposite! Done.

**Review by alancleary — APPROVED** [review]
My bad for not mentioning the change in my review. Thanks for fixing it! This looks ready to go.

**Pull request merged**
