### PR TITLE
Uikit updates

### PR DESCRIPTION
**Pull request by alancleary**
This PR does the following:
* #62
* #71
* Updates the UIkit submodule to the most recent version

A review from @StevenCannon-USDA and/or @maxglycine would be appreciated since this enables a feature they specifically asked for, i.e. changing the color of the links in the tools menu to match the other links on the site.

### CODE REVIEW

**Comment by maxglycine** [comment]
I was not able to see where the sass variables were.  When I went to UIkit/_sass all it had was a symlink.  Let me know where to see this.

**Comment by alancleary** [comment]
> I was not able to see where the sass variables were. When I went to UIkit/_sass all it had was a symlink. Let me know where to see this.

Please try to following the [instructions in the README](https://github.com/legumeinfo/jekyll-theme-legumeinfo/tree/uikit-updates#_sass), i.e. you need to add a `_sass/` directory to your site and then put a `variables.scss` and/or `mixins.scss` file in it to customize the styling.

**Review by StevenCannon-USDA — APPROVED** [review]
Looks good. Tested by changing link colors at jekyll-soybase (branch `font-tweaks`).

**Comment by StevenCannon-USDA** [comment]
Adding a general question about submodules (since this update involves updates to the theme and adds UIkit as a submodule):
What does it mean that a submodule status shows as "modified" after an update? Is this a problem / am I doing this wrong? The example at hand:
```
cd _themes/jekyll-theme-legumeinfo
git checkout uikit-updates
git submodule update --remote assets/uikit

git status
On branch uikit-updates
Your branch is up to date with 'origin/uikit-updates'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   uikit (new commits)

no changes added to commit (use "git add" and/or "git commit -a")

diff --git a/assets/uikit b/assets/uikit
index 02a02b8..f5e9311 160000
--- a/assets/uikit
+++ b/assets/uikit
@@ -1 +1 @@
-Subproject commit 02a02b87264dbc56c11c0701d11b012c576eb876
+Subproject commit f5e9311271ea99b44ffa66ad212e589369f2e758
```

Do I need to tell git to use a particular commit? Also confusing: I don't see those commits in the git log (which probably means that I am looking at the wrong log ...)

**Comment by alancleary** [comment]
@StevenCannon-USDA The theme manages the uikit submodule for you so the `git submodule update` command is not necessary.

In general, I don't recommend updating the uikit submodule in this way. `git submodule update` pulls the most recent commit from the uikit main branch, which contains code that hasn't been released and may included bugs! The theme will always pin the submodule at an officially released version and all code that comes with the theme should be up to date with that specific version of uikit.

**Comment by StevenCannon-USDA** [comment]
@alancleary Thanks. Don't I need to do something, though, to at least tell the site instance (jekyll-soybase) what branch to use in the submodule? And I am still puzzled about the "modified" status for the theme. The following is what I see after adding, committing, and pushing changes to the site -- changes that seem to successfully use the new stuff in the theme's uikit-updates branch.
```
git submodule update

git status
On branch font-tweaks
Your branch is up to date with 'origin/font-tweaks'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   _themes/jekyll-theme-legumeinfo (untracked content)

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by alancleary** [comment]
@StevenCannon-USDA Apparently git doesn't automatically handle moving a submodule into a new directory, i.e. it creates the new submodule folder but doesn't fetch its content and it leaves the older folder as uncommitted files. The following should set you straight:
```console
cd _themes/jekyll-theme-legumeinfo
git fetch --all
git checkout uikit-updates
git submodule update --init
rm -r uikit
```
Sorry for the confusion!

**Comment by StevenCannon-USDA** [comment]
@alancleary Perfect. I've learned something again.

**Pull request merged**
