### PR TITLE
resolving #42

### PR DESCRIPTION
**Pull request by adf-ncgr**
removes the _data subfolder per discussion under #22

### CODE REVIEW

**Review by sammyjava — APPROVED** [review]
Works for me.

**Comment by alancleary** [comment]
Did you test this version of the theme with the jekyll-starter-legumeinfo site? I get the following error when I try building the site with Docker Compose:
```console
Liquid Exception: Liquid syntax error (line 39): Unknown tag 'file_exists' in taxa/arachis/index.html
```

**Comment by sammyjava** [comment]
No, I tested it against my dev site. I do not have `file_exists` in that file or anywhere under `_data`. I think that is probably very old `_data` on the starter site. I can refresh it with the current _data.

**Comment by alancleary** [comment]
> No, I tested it against my dev site. I do not have `file_exists` in that file or anywhere under `_data`. I think that is probably very old `_data` on the starter site. I can refresh it with the current _data.

Yes, please do! This should require updating the version of the theme submodule as well.

**Comment by adf-ncgr** [comment]
I should note that I haven't pushed the updated _data to starter yet, that's a separate PR (which I haven't actually made)

**Comment by sammyjava** [comment]
Yup, I'm getting that same error on the starter site with @adf-ncgr 's new data
```console
  Liquid Exception: Liquid syntax error (line 39): Unknown tag 'file_exists' in taxa/arachis/index.html
```
which I presume is generated by
```
_themes/jekyll-theme-legumeinfo/_layouts/taxon.html:{% capture species_photo %}{% file_exists assets/img/species_images/{{ item["abbrev"] }}.jpg %}{% endcapture %}
```
since that's the only place on the starter site that `file_exists` is present.

My jekyll-legumeinfo instance runs fine because it includes `file_exists` in the Gemfile:
```
Gemfile:  gem 'jekyll_file_exists', :git => 'https://github.com/asperduti/jekyll_file_exists.git'
Gemfile.lock:  remote: https://github.com/asperduti/jekyll_file_exists.git
Gemfile.lock:    jekyll_file_exists (0.1.0)
Gemfile.lock:  jekyll_file_exists!
```
This is NOT present in the starter site's Gemfile.

**Comment by adf-ncgr** [comment]
I don't recall introducing this, although it is ringing a very dim bell; but it sounds like adding it to the starter site's Gemfile may be a fine way to go unless you want me to try to dust off my memory banks further (which I can do later)

**Comment by alancleary** [comment]
> I don't recall introducing this, although it is ringing a very dim bell; but it sounds like adding it to the starter site's Gemfile may be a fine way to go unless you want me to try to dust off my memory banks further (which I can do later)

It sounds like the missing Gem is the issue, which makes sense since you're update was to get the theme in line with what legumeinfo is doing.

**Comment by sammyjava** [comment]
> **Edit:** To clarify, it sounds like the Gem should be installed in the theme.

Ahhh, right. Let me do that in a new theme branch and sally forward.

**Comment by sammyjava** [comment]
I bounced it to you @alancleary in #44 as it doesn't seem to get picked up in the site when it's in the theme the straightforward way I did it. I wonder if the site needs to load gems specified under the theme with some sort of include? Anyway, you'll figure it out.

**Pull request merged**
