### PR TITLE
Add card for displaying a Twitter feed

### PR DESCRIPTION
**Pull request by svengato**

### CODE REVIEW

**Review by alancleary — CHANGES_REQUESTED** [review]
I was able to get the card to appear by setting the `twitter_username` variable in the `_config.yml` file and setting the `twitter_card` variable to `true` in the page front matter. However, no tweets are actually showing up in the card. Additionally, are the card header and footer necessary if we're not using them?

Lastly, please add a commit to the PR that updates the [Front Matter section](https://github.com/legumeinfo/jekyll-theme-legumeinfo#configuration-via-front-matter) of the theme's `README.md` file to document the new `twitter_card` variable.

**Comment by svengato** [comment]
1. What twitter_username did you use? (legumefed should work)
2. The header and footer are not necessary here, I can remove them.
3. It also looks like I need to add something like (page.twitter_card and site.twitter_username) to _layouts/defaults.html to display the card container in case both the News and Announcements cards are turned off. However, there is evidence that parentheses are not valid syntax for nested logical values - looking into that now.
4. This requires me to make another commit to pr-twitter-card, right? (researching that as well)

**Comment by svengato** [comment]
1. I find that if I change anything in _config.yml, I have to restart the site (by ctrl-C, then "bundler exec jekyll serve") to get the changes to appear. But changes to index.html work after refreshing the site. This may explain the invisible Twitter card.

3. Removing the parentheses happens to work in this case, as it evaluates logical operators from right to left.

**Comment by alancleary** [comment]
> 1. What twitter_username did you use? (legumefed should work)

I tried legumefed and legumeinfo. It correctly generated the link to those twitter accounts but no tweets were displayed.

> 2. The header and footer are not necessary here, I can remove them.

Sounds good.

> 3. It also looks like I need to add something like (page.twitter_card and site.twitter_username) to _layouts/defaults.html to display the card container in case both the News and Announcements cards are turned off. However, there is evidence that parentheses are not valid syntax for nested logical values - looking into that now.

Good catch. Maybe don't worry about the username here and update the card to complain that a username hasn't been given instead of not being displayed if the username is missing?

> 4. This requires me to make another commit to pr-twitter-card, right? (researching that as well)

Just push to the same branch and the new commits should be included in the PR. At least I think that's how it works...

**Comment by alancleary** [comment]
@svengato Apparently the Twitter timeline was being blocked by a plugin in my browser; your code works just fine. Sorry for the misdirection, again!

With the timeline working I was able to play with the styling to get it to blend in better with the theme. Here's what I came up with:
```html
<div class="uk-card uk-card-default uk-margin-top uk-padding-remove" style="border-radius: 12px">
  <a class="twitter-timeline uk-padding-small" href="https://twitter.com/{{ site.twitter_username }}" data-tweet-limit=3>Tweets by {{ site.twitter_username }}</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>
```
I dropped all the card contents/padding and rounded the corners to match the timeline's corners. This makes the timeline look like it's the card but it's actually still wrapped in a card to force it to align and scale correctly with the rest of the page.

**Comment by svengato** [comment]
> Maybe don't worry about the username here and update the card to complain that a username hasn't been given instead of not being displayed if the username is missing?

That would fix a missing twitter_username, but not an invalid twitter_username. I guess the solution for the latter is to open a Twitter account for the desired username?

> Just push to the same branch and the new commits should be included in the PR.

How descriptive should the commit message be for these corrections? The entire pull request still comes under "Add card for displaying a Twitter feed", so would a simple "Fix requested issues" be sufficient?

**Comment by alancleary** [comment]
> That would fix a missing twitter_username, but not an invalid twitter_username. I guess the solution for the latter is to open a Twitter account for the desired username?

Ha! Maybe let Twitter handle invalid usernames?

> How descriptive should the commit message be for these corrections? The entire pull request still comes under "Add card for displaying a Twitter feed", so would a simple "Fix requested issues" be sufficient?

I'm of the opinion that all commit messages should be descriptive and not mention anything specific to GitHub. This makes it easier for someone using git from the command-line to understand what's happening just by reading the commit log, no referencing GitHub required!

**Comment by svengato** [comment]
> I'm of the opinion that all commit messages should be descriptive and not mention anything specific to GitHub. This makes it easier for someone using git from the command-line to understand what's happening just by reading the commit log, no referencing GitHub required!

Then it would make sense to make a separate commit for each correction? I will think about it (back later today).

**Comment by alancleary** [comment]
> I'm a big fan of small, single-purpose commits. And with PRs there's no downside, they all get included. Not that I always stick to that.

I agree. This approach also makes it easier to write descriptive commit messages since there's less to describe!

**Review by alancleary — CHANGES_REQUESTED** [review]
The styling of the "No Twitter username" card is inconsistent with the other cards. Honestly, I don't think a whole other card is even necessary here; I would put the if/else block inside of the existing card and only show the Twitter code if the username is set, otherwise just show the "No Twitter username" text. Also, this text should be styled using [UIkit](https://getuikit.com/docs/text#text-color) instead of setting the text color manually (inline style should be avoided in general; I only used it to round the corners because UIkit doesn't have built-in support for that).
```html
{% if site.twitter_username %}
<a class="uk-padding-small twitter-timeline" href="https://twitter.com/{{ site.twitter_username }}" data-tweet-limit=3>Tweets by {{ site.twitter_username }}</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
{% else %}
<span class="uk-padding-small uk-text-danger">No Twitter username provided</span>
{% endif %}
```

**Comment by alancleary** [comment]
It turns out the header and footer can be removed from the Twitter timeline widget [via additional data attributes](https://developer.twitter.com/en/docs/twitter-for-websites/timelines/guides/parameter-reference). Instead of endlessly asking you to tweak this PR [I just made a branch](https://github.com/legumeinfo/jekyll-theme-legumeinfo/tree/pr-twitter-card-styled) that removes the header and footer so the timeline styling can really look like the news and announcements cards. (The branch also disables tracking by Twitter, which is apparently enabled by default...) Anyway, have a look and if all seems well I'll merge it into this branch and then merge the PR. Thanks for you patience!

**Comment by alancleary** [comment]
I'll just push a commit to that PR that corrects the issue. Standby for merges!

**Review by alancleary — APPROVED** [review]
Everything looks good. Thanks for doing this, @svengato!

**Pull request merged**
