### PR TITLE
Make some other global font sizes configurable

### PR DESCRIPTION
**Pull request by svengato**

### CODE REVIEW

**Comment by svengato** [comment]
For issue #27.

**Review by alancleary — CHANGES_REQUESTED** [review]
@svengato Is there a reason the `xxlarge_font_size` variable uses `xx` instead of `2x` like the UIkit SCSS?

Also, please add the previously hard-coded values as the default values for the new variables in the theme's `_config.yml` file.

**Comment by svengato** [comment]
> Is there a reason the xxlarge_font_size variable uses xx instead of 2x like the UIkit SCSS?

Variable names (this in in YAML) cannot start with a number, can they? In UIkit they are like "global-2xlarge" which is okay.

**Review by alancleary — CHANGES_REQUESTED** [review]
Thanks for the changes @svengato. Now can you merge main into this branch? The code formatting in the `_config.yml` section is different in this branch than what's in main so letting this PR auto-merge will probably mix styles!

**Comment by alancleary** [comment]
> do you mean merge 'main' into (-->) 'more-configurable-font-sizes'?

Yes, merge main into more-configurable-font-sizes.

> It seems like that could mess things up, but I can try it on a copy first.

My point exactly. If merging is going to mess things up we should do it in a branch that's not main. Give it a go!

**Comment by svengato** [comment]
`README.md` is the only file with conflicts. Now trying to understand the changes before merging. I think I prefer Sam's formatting changes, like

```
* `title`: String (the title)
```
instead of
```
* `title: String (the title)`
```

**Comment by alancleary** [comment]
> `README.md` is the only file with conflicts. Now trying to understand the changes before merging. I think I prefer Sam's formatting changes, like
> 
> ```
> * `title`: String (the title)
> ```
> 
> instead of
> 
> ```
> * `title: String (the title)`
> ```

Great, because I'm asking you to match the format that's currently in main!

**Comment by svengato** [comment]
For the description of default `font_family`, I put "depends on available fonts". All other descriptions are straightforward.

**Comment by svengato** [comment]
Commit [8391bf2](https://github.com/legumeinfo/jekyll-theme-legumeinfo/pull/37/commits/8391bf2b94f2d441f04e59fbf9fd732574b6f430): I had not pulled the latest changes to `main`, it merged after I resolved the conflicts in `README.md` but was 5 commits behind.

Commit [227b2fa](https://github.com/legumeinfo/jekyll-theme-legumeinfo/pull/37/commits/227b2fa3ec31bbad2e25686dc3d7631fed98804a): Checked out `main` and pulled the latest changes. Now this branch is up to date.

**Review by alancleary — APPROVED** [review]

**Pull request merged**
