### PR TITLE
Events

### PR DESCRIPTION
**Pull request by alancleary**
This PR updates the announcements to be used for events instead. News posts should be used for announcements moving forward. (Please see the readme for details on how to use the new events). The events are displayed in reverse chronological order so upcoming and most recent events are shown first. Additionally, JavaScript is used to keep the events lists up to date so that the site doesn't need to be rebuilt just to move an event from one list to the other after the event has occurred.

@svengato and @sdash-github please review/test the changes to make sure this is what you wanted. You'll need to pull this theme branch in the starter site or peanutbase yourselves for testing.

### CODE REVIEW

**Comment by svengato** [comment]
I changed all `announcement(s)` to `event(s)` and can see the old events under "More Events". However, I created a new event with a future date and cannot see it so far - the Events card is blank. I will check again, maybe I am missing something.

**Comment by svengato** [comment]
Suppose I create an upcoming event called Pi Day, 2023-03-14. Under the current logic,
1. To view it as an upcoming event, I have to set the file date today or in the past, say `events/_posts/2023-02-22-test.md`. This is okay, it is the day I created the event.
2. If I then set `date` to 2023-03-14 in the file, the event does not display (because it is thought to be in the future?).
3. If I set only `end_date` to 2023-03-14 in the file, the event displays as expected but lasts from 22 Feb-14 Mar.
4. If I set both `date` and `end_date`, the event displays only if `date` is today or in the past.

So there is something wrong with the logic of displaying upcoming events. I am looking in the _themes/jekyll-legumeinfo code.

**Comment by alancleary** [comment]
@svengato Try using the `--future` flag with the `jekyll` command, e.g. `jekyll serve --incremental --livereload --future`. And don't add a `date` field inside the file. The start date should be encoded in the filename. If there's an end date, then that should be encoded inside the file using the `end_date` field.

**Comment by svengato** [comment]
Is there a way to use the `--future` flag with Docker?

**Comment by alancleary** [comment]
> Is there a way to use the `--future` flag with Docker?

If you're using Docker Compose like the starter site, then override the command in the compose file:
```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 981a558..fd5e8aa 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -9,7 +9,7 @@ services:
     environment:
       VERBOSE: 1
 #     FORCE_POLLING: 1
-    command: jekyll serve --incremental --livereload
+    command: jekyll serve --incremental --livereload --future
     ports:
       - "4000:4000"
       - "35729:35729"
```

**Comment by svengato** [comment]
The internet suggests `future: true` in `_config.yml` ... this indeed works! Thanks -

**Comment by svengato** [comment]
Or is doing it in `docker-compose.yml` preferable?

**Comment by alancleary** [comment]
> The internet suggests `future: true` in `_config.yml` ... this indeed works! Thanks -
> ...
> Or is doing it in `docker-compose.yml` preferable?

I actually set `future: true` in the theme's [` _config.yml` file](https://github.com/legumeinfo/jekyll-theme-legumeinfo/blob/188838b1996eaa0efea7de5488e3deec2cdc4bd4/_config.yml#L31). I guess for some reason that setting doesn't carry over into the site... I would say it's preferable to set `future: true` in your site's `_config.yml` file so future posts will always be included no matter how you're building the site: command-line, docker, docker compose, etc.

**Comment by svengato** [comment]
More tests reveal that with or without `--livereload` in `docker-compose.yml` instead of `_config.yml`, it does not work. So I will just add `--future` to `_config.yml`.

I started the site with `docker-compose up -d` but have since been reloading it using `docker exec jekyll-peanutbase-jekyll-1 jekyll build`.

**Review by svengato — APPROVED** [review]
This works now, @sdash-github  is adding <strike>Announcements</strike> Events as we speak.

**Comment by alancleary** [comment]
> This works now, @sdash-github is adding Announcements Events as we speak.

Thanks for approving. I was just writing you both an email saying that events shouldn't be added before this is merged into master...

I'll add a commit that updates the readme to mention the `future` config and then update the starter site after merging.

**Comment by sdash-github** [comment]
I am done with adding events for today. Sven can now do his git 
jugglery. Please let me know when you have made it ready and then I can 
add more event items. Not before tomorrow anyway.

Sudhansu

**Comment by alancleary** [comment]
> My plan is to do some Git cleanup before committing any Event-related changes. For testing, I did a simple `mv announcements/ events/` but I should really `mv` it back, then do `git mv announcements/ events/`

See PR legumeinfo/jekyll-starter-legumeinfo#1 for what all needs to be changed to migrate from announcements to events.

**Comment by sdash-github** [comment]
We need some locally configurable Paramus for how many events/news items to
display in the corresponding cards.

**Comment by alancleary** [comment]
This feature was already requested and implemented. See `card_item_limit` in the [`_config.yml`](https://github.com/legumeinfo/jekyll-theme-legumeinfo#_configyml) section of the readme. Setting this variable in the config file will set how many items are displayed in every card. If you want to control this on a per-card basis then open a new issue.

**Comment by svengato** [comment]
Before committing the Events changes, there is still one thing I do not understand. After updating the Jekyll theme by a `git pull` (and confirming that the PeanutBase Jekyll site still works), one line of `git status` now shows
`	modified:   _themes/jekyll-theme-legumeinfo (new commits)`

Do I just need to `git add _themes/jekyll-theme-legumeinfo` along with the other changes, or is something more complicated required?

**Comment by svengato** [comment]
> Do I just need to git add _themes/jekyll-theme-legumeinfo along with the other changes, or is something more complicated required?

Like doing
`git submodule update --init --recursive`
?

**Comment by alancleary** [comment]
> Do I just need to `git add _themes/jekyll-theme-legumeinfo` along with the other changes

This

**Comment by svengato** [comment]
Done.

**Pull request merged**
