### PR TITLE
replacing the earlier taxon layout with one copied from jekyll-legume…

### PR DESCRIPTION
**Pull request by adf-ncgr**
…info that works with the yml produced by the lis-autocontent tool

### CODE REVIEW

**Review by alancleary — APPROVED** [review]
This seems fine to me. Does any of the example data in `_data/` need to be updated?

**Comment by adf-ncgr** [comment]
good call, I hadn't thought about that. I'll do that before merging

**Comment by sammyjava** [comment]
I'm out of the loop on this, I presume we're transitioning to lis-autocontent to generate the YAML rather than using my Python scripts in the LIS site's _scripts directory for the LIS site. Which is great, just wondering if that's what's going on.

**Comment by adf-ncgr** [comment]
@sammyjava not quite, the autocontent stuff was developed from your code and I believe produces the same structure. The problem this is trying to address is that the theme was using a different structure, so IIRC this update was simply updating the theme to be consistent with what you had done. But obviously I'm not quite on top of it considering that I seem to have effectively ignored @alancleary trying to bump it into my attention zone. Will try to wrap it up ASAP

**Comment by adf-ncgr** [comment]
@alancleary I finally did the _data update here (yes, it's a long ASAP) but now I'm realizing that [the starter site repo](https://github.com/legumeinfo/jekyll-starter-legumeinfo) has its own _data folder containing the same obsolete content I just updated here. Do we really need to have both?

**Comment by alancleary** [comment]
@adf-ncgr I believe the `_data` directory was added to the theme because @nathanweeks was trying to run the theme directly as a Jekyll site sometime early in its development. The lack of a `_data` directory was causing problems because there was nothing for the data-page-generator to parse.

I don't know if there's still a compelling reason to run the theme directly as a Jekyll site but I'm inclined to do away with its `_data` directory in preference for the `_data` directory in the starter site. For now, though, it's probably worth merging this PR and replicating the changes in the starter site.

**Comment by adf-ncgr** [comment]
OK, sounds good. I was mostly asking because I wasn't sure how to test the changes in a theme-only context. I'm still not sure but I'll just go ahead with it and make an issue regarding possible future deletion of the example data from this context.

**Comment by alancleary** [comment]
> OK, sounds good. I was mostly asking because I wasn't sure how to test the changes in a theme-only context. I'm still not sure but I'll just go ahead with it and make an issue regarding possible future deletion of the example data from this context.

I think this is why Nathan was trying to run the theme directly like a Jekyll site. Personally I do all my theme development inside the submodule of the starter so I can test it via the starter. It also helps me keep the starter up to date with the theme, although I've gotten bad about that lately...

**Comment by sammyjava** [comment]
I think folks should be forced to use the theme as a _theme under a site_ for testing, not as a standalone site. Its themeyness is a big part of what you're testing. (This was, of course, important when I was getting jekyll-legumeinfo back onto the theme.)

So definitely yank _data from the theme. I forgot that it's even in there. But the starter site should have some example _data, of course.

**Comment by alancleary** [comment]
> I think folks should be forced to use the theme as a _theme under a site_ for testing, not as a standalone site. Its themeyness is a big part of what you're testing. (This was, of course, important when I was getting jekyll-legumeinfo back onto the theme.)
> 
> So definitely yank _data from the theme. I forgot that it's even in there. But the starter site should have some example _data, of course.

This is pretty much how I feel. The starter site is basically test code for the theme so any changes that happen in the theme will need to be verified in the starter site anyway. Let's yank `_data`!

**Pull request merged**
